name: 'Feature Request'
description: Suggest a feature for NxArch Library

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which @nxarch/* package(s) are relevant/related to the feature request?
      options:
        - ng-nest
        - other
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: true

  - type: dropdown
    id: contribute
    attributes:
      label: Do you want to create a pull request?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
