name: '@nxarch/nxarch'

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!release'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node_version: [14]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: https://registry.npmjs.org

      - name: npm install
        shell: bash
        run: npm run install --legacy-peer-deps

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint:affected

      - name: Test
        run: npm run test:affected

      - name: Build
        run: npm run build:affected
